# Site settings
title: Pablo Jorge's blog
email:
description: Random writings
baseurl: ""
url: "https://pablojorge.github.io/"
twitter_username: pablohjorge
github_username:  pablojorge
google_analytics: UA-37907185-2

# Build settings
theme: minima
plugins:
  - jekyll-feed